// Service worker: app shell and data are precached so calculators and texts
// work offline. Network-first keeps content fresh when online.
// PRECACHE and CACHE_VERSION are generated by tools/update-precache.mjs.
const CACHE_VERSION = 'da-d9e3c2d623e8';

const PRECACHE = [
  './',
  'assets/diagrams/a4c.svg',
  'assets/diagrams/cw.svg',
  'assets/diagrams/ivc.svg',
  'assets/diagrams/mitral.svg',
  'assets/diagrams/mmode.svg',
  'assets/diagrams/peri.svg',
  'assets/diagrams/plax.svg',
  'assets/diagrams/psax.svg',
  'assets/diagrams/tdi.svg',
  'assets/icons/app-icon-maskable.svg',
  'assets/icons/app-icon.svg',
  'assets/icons/sprite.svg',
  'config/app.json',
  'css/base.css',
  'css/tokens.css',
  'data/cases/demo-1.json',
  'data/formulas/diastolic.json',
  'data/formulas/ef-simpson.json',
  'data/formulas/ef-teichholz.json',
  'data/formulas/index.json',
  'data/formulas/lvmass-rwt.json',
  'data/formulas/pasp.json',
  'data/formulas/rap-ivc.json',
  'data/i18n/en.json',
  'data/i18n/ru.json',
  'data/i18n/uz.json',
  'data/navigation.json',
  'data/parameters.json',
  'data/plans.json',
  'data/providers.json',
  'data/rules.json',
  'data/sources.json',
  'data/specialties.json',
  'data/thresholds.json',
  'index.html',
  'js/api/demo.js',
  'js/api/http.js',
  'js/api/index.js',
  'js/app.js',
  'js/core/ai-guard.js',
  'js/core/calc.js',
  'js/core/config.js',
  'js/core/expr.js',
  'js/core/i18n.js',
  'js/core/measurements.js',
  'js/core/policy.js',
  'js/core/rules.js',
  'js/core/service.js',
  'js/core/storage.js',
  'js/core/store.js',
  'js/core/thresholds.js',
  'js/theme-init.js',
  'js/ui/dom.js',
  'js/ui/format.js',
  'js/ui/modal.js',
  'js/views/account.js',
  'js/views/admin-limits.js',
  'js/views/admin.js',
  'js/views/assistant.js',
  'js/views/calculators.js',
  'js/views/common.js',
  'js/views/conclusion.js',
  'js/views/echo.js',
  'js/views/home.js',
  'js/views/index.js',
  'js/views/param-modal.js',
  'js/views/param-text.js',
  'js/views/plans.js',
  'js/views/questions.js',
  'manifest.webmanifest',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_VERSION)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE_VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);
  // Only same-origin GETs; API calls (server/ proxy) are never cached.
  if (request.method !== 'GET' || url.origin !== self.location.origin || url.pathname.startsWith('/api/')) {
    return;
  }
  event.respondWith(
    fetch(request)
      .then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE_VERSION).then((cache) => cache.put(request, copy));
        }
        return response;
      })
      .catch(() => caches.match(request, { ignoreSearch: true })
        .then((cached) => cached || (request.mode === 'navigate' ? caches.match('index.html') : Response.error()))),
  );
});
